/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/projects": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["storage.Project"][];
        };
        default: {
          schema: definitions["restapi.ResponseError"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Project Create Params */
          params: definitions["storage.ProjectCreateParams"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["storage.CreatedItem"];
        };
        default: {
          schema: definitions["restapi.ResponseError"];
        };
      };
    };
  };
  "/users": {
    post: {
      parameters: {
        body: {
          /** User Create Params */
          params: definitions["storage.UserCreateParams"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["storage.CreatedItem"];
        };
        default: {
          schema: definitions["restapi.ResponseError"];
        };
      };
    };
  };
  "/users/{id}": {
    get: {
      parameters: {
        path: {
          /** User ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["storage.User"];
        };
        default: {
          schema: definitions["restapi.ResponseError"];
        };
      };
    };
  };
}

export interface definitions {
  "restapi.ResponseError": {
    Error?: string;
  };
  "storage.CreatedItem": {
    ID?: number;
  };
  "storage.Project": {
    CreatedAt?: string;
    CreatedBy?: number;
    Description?: string;
    ID?: number;
    Title?: string;
    UpdatedAt?: string;
    UpdatedBy?: number;
  };
  "storage.ProjectCreateParams": {
    CreatedBy?: number;
    Description?: string;
    Title?: string;
  };
  "storage.User": {
    CreatedAt?: string;
    ID?: number;
    Login?: string;
    Password?: string;
    UpdatedAt?: string;
  };
  "storage.UserCreateParams": {
    Login?: string;
    Password?: string;
  };
}

export interface operations {}

export interface external {}
