definitions:
  restapi.ResponseError:
    properties:
      Error:
        type: string
    type: object
  storage.CreatedItem:
    properties:
      ID:
        type: integer
    type: object
  storage.Project:
    properties:
      CreatedAt:
        type: string
      CreatedBy:
        type: integer
      Description:
        type: string
      ID:
        type: integer
      Title:
        type: string
      UpdatedAt:
        type: string
      UpdatedBy:
        type: integer
    type: object
  storage.ProjectCreateParams:
    properties:
      CreatedBy:
        type: integer
      Description:
        type: string
      Title:
        type: string
    type: object
  storage.User:
    properties:
      CreatedAt:
        type: string
      ID:
        type: integer
      Login:
        type: string
      Password:
        type: string
      UpdatedAt:
        type: string
    type: object
  storage.UserCreateParams:
    properties:
      Login:
        type: string
      Password:
        type: string
    type: object
info:
  contact: {}
paths:
  /projects:
    get:
      operationId: GetProjectsAll
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.Project'
            type: array
        default:
          description: ""
          schema:
            $ref: '#/definitions/restapi.ResponseError'
    post:
      consumes:
      - application/json
      operationId: PostProject
      parameters:
      - description: Project Create Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/storage.ProjectCreateParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.CreatedItem'
        default:
          description: ""
          schema:
            $ref: '#/definitions/restapi.ResponseError'
  /users:
    post:
      consumes:
      - application/json
      operationId: PostUser
      parameters:
      - description: User Create Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/storage.UserCreateParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.CreatedItem'
        default:
          description: ""
          schema:
            $ref: '#/definitions/restapi.ResponseError'
  /users/{id}:
    get:
      operationId: GetUserByID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/restapi.ResponseError'
swagger: "2.0"
